downstream_package_name: blivet-gui
jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-29-x86_64
    - fedora-30-x86_64
    - fedora-31-x86_64
    - fedora-rawhide-x86_64
  trigger: pull_request
specfile_path: blivet-gui.spec
synced_files:
- blivet-gui.spec
- .packit.yaml
upstream_package_name: blivet-gui
