downstream_package_name: blivet-gui
jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-all
  trigger: pull_request
specfile_path: blivet-gui.spec
synced_files:
- blivet-gui.spec
- .packit.yaml
upstream_package_name: blivet-gui
current_version_command: ["python3", "setup.py", "--version"]
create_tarball_command: ["make", "local"]
